language: python
python:
  - "3.6"


matrix: 
  include: 
    - dist: bionic 
    - dist: xenial
    
services: 
  - docker

before_script: pip install docker-compose

script: 
  - docker-compose run app sh -c "python manage.py test" 